version: "3.7"

services:
  postgre_db:
    image: postgre_db
    container_name: postgre_db
    build: ./postgre_db
    env_file: .env
    restart: always
    networks:
      - trans_network
  back_end:
    image: back_end
    container_name: back_end
    build: ./back_end
    depends_on:
      - postgre_db
    restart: always
    networks:
      _ trans_network
  nginx:
    image: nginx
    container_name: nginx
    build: ./server
    depends_on:
      - back_end
    restart: always
    ports:
      - "80:80"
    networks:
      - trans_network

networks:
  trans_network:
    driver: bridge